routes:
    home:                   'Default:home:both'
    logout:                 'User:logout:connected'
    login:                  'User:login:disconnected'
    register:               'User:register:disconnected'
    changePassword:         'User:changePassword:connected'
    changeUsername:         'User:changeUsername:connected'
    sendMessage:            'Message:sendMessage:connected'
defaut_route: 'home'
