routes: #todo take out useless routes ; reorganize controller (one controller for modale, for example?
    home:                    'Default:showHomePage:both:get' #todo misses picture. See link as well
    about:                   'Default:showAboutPage:both:get'
    forum:                   'Default:showForumPage:both:get' #not functional
    contact:                 'Default:showContactPage:both:get' #not functionnal
    searchProForm:           'Default:seeSearchProForm:connected:get'
    getSignInModal:          'Default:showSignIn:disconnected:get'
    getSignUpModal:          'Default:showSignUp:disconnected:get'
    getProSignUpModal:       'Default:showProSignUp:disconnected:get'
    getVictimSignUpModal:    'Default:showVictimSignUp:disconnected:get'
    legalNotice:             'Default:getLegalNoticePage:both:get'
    proList:                 'Default:getProfessionalList:both:get'
    documentation:           'Default:showDocPage:both:get'
    logout:                  'User:logout:connected:post'
    login:                   'User:login:disconnected:post'
    changeData:              'User:changeData:connected:post'
    sendMessage:             'Message:sendMessage:connected:post'
    # getReceivedMessage:     'Message:getReceivedMessage:connected:get'
    # getSentMessage:         'Message:getSentMessage:connected:get'
    downloadPj:              'Message:downloadPj:connected:get'
    suppressMessage:         'Message:suppressMessage:connected:post'
    # changeFreeSlot:         'Pro:changeFreeSlot:connected:post'
    findAutoPro:             'Pro:findAutoProfessional:connected:post'
    findUsernamePro:         'Pro:findUsernameProfessional:connected:post'
    proSuccess:              'Default:showProSuccess:connected:get'
    abandonPro:              'Pro:abandonProfessional:connected:post'
    proInscription:          'User:professionalInscription:disconnected:post'
    victimInscription:       'User:victimInscription:disconnected:post'
    activateAccount:         'User:activateAccount:admin:post'
    suppressAccount:         'User:suppressAccount:connected:post'
    rejectPro:               'Pro:suppressCandidate:admin:post'
    account:                 'Default:showAccountPage:connected:get'
    accountModif:            'Default:showModifAccountPage:connected:get'
    inbox:                   'Message:showInbox:connected:get'
    showSendingMessageForm:  'Message:sendMessageForm:connected:get'
    showEmail:               'Message:showEmail:connected:get'
    consultSentMessage:      'Message:showSentMessage:connected:get'
    confirmSuppressionModal: 'Default:showConfirmSuppressionModal:both:get'
    getLogs:                 'Default:getLogs:admin:post'
    seeLogTwig:              'Default:showLogPage:admin:get'
    seeUserList:             'Default:seeUserPage:admin:get'
    getUserList:             'Default:getUserList:admin:post'
    suppressionMessageModal: 'Default:getSuppressionMessage:admin:get'
    # getUserData:            'User:showUserData:connected:get' not decided yet
defaut_route: 'home'
