routes:
    home:                   'Default:showHomePage:both:get' #todo misses picture. See link as well
    about:                  'Default:showAboutPage:both:get'
    forum:                  'Default:showForumPage:both:get' #not functional
    contact:                'Default:showContactPage:both:get' #not functionnal
    documentation:          'Default:showDocPage:both:get'
    logout:                 'User:logout:connected:post'
    login:                  'User:login:disconnected:post'
    register:               'User:register:disconnected:post'
    changeData:             'User:changeData:connected:post'
    sendMessage:            'Message:sendMessage:connected:post'
    getReceivedMessage:     'Message:getReceivedMessage:connected:get'
    getSentMessage:         'Message:getSentMessage:connected:get'
    downloadPj:             'Message:downloadPj:connected:post'
    suppressMessage:        'Message:suppressMessage:connected:post'
    changeFreeSlot:         'Pro:changeFreeSlot:connected:post'
    findPro:                'Pro:findProfessional:connected:post'
    abandonPro:             'Pro:abandonProfessional:connected:post'
    proInscription:         'User:professionalInscription:disconnected:post'
    victimInscription:      'User:victimInscription:disconnected:post'
    activateAccount:        'User:activateAccount:connected:post'
    suppressAccount:        'User:suppressAccount:connected:post'
    rejectPro:              'Pro:suppressCandidate:connected:post'
defaut_route: 'home'
